# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:7559eaa667fca92b41dd4d9481a1ac070f112c767b1ad24e499bc05cbadb79ee

COPY ui/dist/ .
COPY images/sbomer-ui/run-with-env.sh /deployments/run-with-env.sh

USER root

RUN chown 1001:0 /opt/app-root/src/config.js && \
    chmod ug+rw /opt/app-root/src/config.js && \
    chmod 755 /deployments/run-with-env.sh

USER 1001

ENTRYPOINT ["/deployments/run-with-env.sh"]
