# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:99d8a1d13835606114bb7785056793903c8739b7e1213b549f82ef30e0d51e5d

COPY ui/dist/ .
COPY images/sbomer-ui/run-with-env.sh /deployments/run-with-env.sh

USER root

RUN chown 1001:0 /opt/app-root/src/config.js && \
    chmod ug+rw /opt/app-root/src/config.js && \
    chmod 755 /deployments/run-with-env.sh

USER 1001

ENTRYPOINT ["/deployments/run-with-env.sh"]
