# https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
FROM registry.access.redhat.com/ubi9/nginx-120@sha256:bb6e7418d2667478618f63d21522a8c3a5f8e0bea99d94bbc890fbed053d793b

COPY ui/dist/ .
COPY images/sbomer-ui/run-with-env.sh /deployments/run-with-env.sh

USER root

RUN chown 1001:0 /opt/app-root/src/config.js && \
    chmod ug+rw /opt/app-root/src/config.js && \
    chmod 755 /deployments/run-with-env.sh

USER 1001

ENTRYPOINT ["/deployments/run-with-env.sh"]
